SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;

SELECT T1.NAME
FROM CITY T1
INNER JOIN COUNTRY T2 ON T2.CODE = T1.COUNTRYCODE
WHERE T2.CONTINENT = 'Africa';

exit;