SELECT
    C.COMPANY_CODE, C.FOUNDER
    , COUNT(DISTINCT LM.LEAD_MANAGER_CODE)
    , COUNT(DISTINCT SM.SENIOR_MANAGER_CODE)
    , COUNT(DISTINCT M.MANAGER_CODE)
    , COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY C
LEFT JOIN LEAD_MANAGER LM ON LM.COMPANY_CODE = C.COMPANY_CODE
LEFT JOIN SENIOR_MANAGER SM ON
    SM.COMPANY_CODE = C.COMPANY_CODE
    AND SM.LEAD_MANAGER_CODE = LM.LEAD_MANAGER_CODE
LEFT JOIN MANAGER M ON
    M.COMPANY_CODE = C.COMPANY_CODE
    AND M.LEAD_MANAGER_CODE = LM.LEAD_MANAGER_CODE
    AND M.SENIOR_MANAGER_CODE = SM.SENIOR_MANAGER_CODE
LEFT JOIN EMPLOYEE E ON
    E.COMPANY_CODE = C.COMPANY_CODE
    AND E.LEAD_MANAGER_CODE = LM.LEAD_MANAGER_CODE
    AND E.SENIOR_MANAGER_CODE = SM.SENIOR_MANAGER_CODE
    AND E.MANAGER_CODE = M.MANAGER_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
ORDER BY C.COMPANY_CODE;