SELECT CITY, LENGTH(CITY)
FROM (
	SELECT CITY FROM STATION T1
	WHERE LENGTH(CITY) = (
        SELECT MIN(LENGTH(T2.CITY)) FROM STATION T2
    )
	ORDER BY CITY
)
WHERE ROWNUM = 1
UNION
SELECT CITY, LENGTH(CITY)
FROM (
	SELECT CITY
	FROM STATION T1
	WHERE LENGTH(CITY) = (
        SELECT MAX(LENGTH(T2.CITY)) FROM STATION T2
    )
	ORDER BY CITY
)
WHERE ROWNUM = 1;