SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;

/*
Enter your query here.
Please append a semicolon ";" at the end of the query and enter your query in a single line to avoid error.
*/

SELECT CITY, LENGTH(CITY) FROM (SELECT CITY FROM STATION T1 WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(T2.CITY)) FROM STATION T2) ORDER BY CITY) WHERE ROWNUM = 1 UNION SELECT CITY, LENGTH(CITY) FROM (SELECT CITY FROM STATION T1 WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(T2.CITY)) FROM STATION T2) ORDER BY CITY) WHERE ROWNUM = 1;

exit;