SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;

SELECT T1.CONTINENT, FLOOR(AVG(T2.POPULATION))
FROM COUNTRY T1
INNER JOIN CITY T2 ON T1.CODE = T2.COUNTRYCODE
GROUP BY T1.CONTINENT;

exit;